### ISSUE TITLE
errors in tests

### ISSUE THREAD

**Issue by zanat** [tkotani/ecalj#6]
I have this error 
/home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/bin/lmfa copt -vnsp=2 -cstrx=l12 --pr41,41 -vmet=3 -vtetra=0 -vnk1=2 -vlfrce=12 -vdist=1 --rs=0 -vnit=3 --time=5 --no-iactiv > out.lmf.copt 2>&1
mpirun -np 4 /home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/bin/lmf-MPIK  copt -vnsp=2 -cstrx=l12 --pr41,41 -vmet=3 -vtetra=0 -vnk1=2 -vlfrce=12 -vdist=1 --rs=0 -vnit=3 --time=5 --no-iactiv --cvK:158,790 -vpwmode=0 >> out.lmf.copt 2>&1
make[1]: *** [copt.exec] Error 29
make[1]: Leaving directory `/home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/work/copt'
make: *** [copt] Error 2
the error is : 
forrtl: No such file or directory
forrtl: severe (29): file not found, unit 13, file /home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/work/copt/temptempxxx.CODES_install/00_new/ecalj/ecalj/TestInstall/work/copt/temptempxxx.copt

**Comment by tkotani** [comment]
Wait. I reproduced it here.
takao

2015-03-05 1:51 GMT+09:00 zanat <notifications@github.com>:

> I have this error
> /home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/bin/lmfa copt
> -vnsp=2 -cstrx=l12 --pr41,41 -vmet=3 -vtetra=0 -vnk1=2 -vlfrce=12 -vdist=1
> --rs=0 -vnit=3 --time=5 --no-iactiv > out.lmf.copt 2>&1
> mpirun -np 4
> /home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/bin/lmf-MPIK copt
> -vnsp=2 -cstrx=l12 --pr41,41 -vmet=3 -vtetra=0 -vnk1=2 -vlfrce=12 -vdist=1
> --rs=0 -vnit=3 --time=5 --no-iactiv --cvK:158,790 -vpwmode=0 >>
> out.lmf.copt 2>&1
> make[1]: *** [copt.exec] Error 29
> make[1]: Leaving directory
> `/home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/work/copt'
> make: *** [copt] Error 2
> the error is :
> forrtl: No such file or directory
> forrtl: severe (29): file not found, unit 13, file
> /home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/work/copt/temptempxxx.CODES_install/00_new/ecalj/ecalj/TestInstall/work/copt/temptempxxx.copt
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tkotani/ecalj/issues/6>.
>



-- 
==========================================
Takao Kotani, Tottori University, Japan, tel 0857-31-6741
Address: See right top in http://www.damp.tottori-u.ac.jp/

**Comment by tkotani** [comment]
Dear zanat,
There is a minor bug related to new minor development...
Could you try it again?
(git pull or git pull origin master,
 after you did git stash or something if you add changes to original).
Thank you for your information.

reagars,
takao

2015-03-05 2:34 GMT+09:00 Takao Kotani <takaokotani@gmail.com>:

> Wait. I reproduced it here.
> takao
>
> 2015-03-05 1:51 GMT+09:00 zanat <notifications@github.com>:
>
>> I have this error
>> /home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/bin/lmfa copt
>> -vnsp=2 -cstrx=l12 --pr41,41 -vmet=3 -vtetra=0 -vnk1=2 -vlfrce=12 -vdist=1
>> --rs=0 -vnit=3 --time=5 --no-iactiv > out.lmf.copt 2>&1
>> mpirun -np 4
>> /home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/bin/lmf-MPIK copt
>> -vnsp=2 -cstrx=l12 --pr41,41 -vmet=3 -vtetra=0 -vnk1=2 -vlfrce=12 -vdist=1
>> --rs=0 -vnit=3 --time=5 --no-iactiv --cvK:158,790 -vpwmode=0 >>
>> out.lmf.copt 2>&1
>> make[1]: *** [copt.exec] Error 29
>> make[1]: Leaving directory
>> `/home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/work/copt'
>> make: *** [copt] Error 2
>> the error is :
>> forrtl: No such file or directory
>> forrtl: severe (29): file not found, unit 13, file
>> /home/zanat/CODES_install/00_new/ecalj/ecalj/TestInstall/work/copt/temptempxxx.CODES_install/00_new/ecalj/ecalj/TestInstall/work/copt/temptempxxx.copt
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/tkotani/ecalj/issues/6>.
>>
>
>
>
> --
> ==========================================
> Takao Kotani, Tottori University, Japan, tel 0857-31-6741
> Address: See right top in http://www.damp.tottori-u.ac.jp/
>
>


-- 
==========================================
Takao Kotani, Tottori University, Japan, tel 0857-31-6741
Address: See right top in http://www.damp.tottori-u.ac.jp/

**Comment by zanat** [comment]
Dear Takao,
the bug is fixed thank you
